<?php
// $Id: userpoints_pageviews.module,v 1.1.4.1 2008-12-04 03:09:46 kbahey Exp $

define('USERPOINTS_PAGE_VIEWS', 'userpoints_pageviews');

function userpoints_pageviews_userpoints($op = 'setting', $points = 0, $uid = 0, $event = NULL) {
  if ($op == 'setting') {
    $group = 'pageviews';
    $form[$group] = array(
      '#type'        => 'fieldset',
      '#collapsible' => TRUE,
      '#collapsed'   => TRUE,
      '#title'       => t('!Points for node page views', userpoints_translation()),
    );

    $form[$group][USERPOINTS_PAGE_VIEWS] = array(
      '#type'          => 'textfield',
      '#title'         => t('!Points for node page views', userpoints_translation()),
      '#default_value' => variable_get(USERPOINTS_PAGE_VIEWS , 0),
      '#size'          => 5,
      '#maxlength'     => 5,
    );
    return $form;
  }
}

function userpoints_pageviews_nodeapi(&$node, $op = 'view', $teaser, $page) {
  global $user;

  switch($op) {
    case 'view':
      if ($page) {
        // Node is being viewed in page mode, not in a list
        if ($user->uid) {
          // The user is logged in, not anonymous
          if ($node->uid !== $user->uid) {
            // The user did not not create this node...
            userpoints_userpointsapi(array(
              'uid' => $node->uid,
              'points' => variable_get(USERPOINTS_PAGE_VIEWS, 0),
              ));
          }
        }
      }
  }
}
